name: SonarQube

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6

      - name: Add Build Wrapper to PATH
        run: |
          echo "/home/runner/work/_temp/build-wrapper-linux-x86" >> $GITHUB_PATH
          ls -la /home/runner/work/_temp/build-wrapper-linux-x86

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ ninja-build

      # Juliet NORMAL build (not CHERI)
      - name: Run Build Wrapper with CMake
        run: |
          mkdir build
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} \
            cmake -S . -B build
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} \
            cmake --build build -j 2

      - name: Check compile_commands.json
        run: |
          ls -la ${{ env.BUILD_WRAPPER_OUT_DIR }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
